const youtube_videos_obj = [
  {
    kind: "youtube#video",
    etag: "kNw4n-TlShV5JCE6WYPDw0ieQnM",
    id: "7Dt3iZluYgA",
    snippet: {
      publishedAt: "2024-03-14T19:54:40Z",
      channelId: "UCRs1pHnES3QDdh43xbjOmzw",
      title: "CrossFit Open Workout 24.3 Live Announcement",
      description:
        "Week 3 of the 2024 CrossFit Open will close out with a bang!\n\nA new matchup will take place for the live announcement of Open Workout #24point3 — get ready to close out the 2024 CrossFit Open with Arielle Loewen, Sydney Wells, Jay Crouch, and Roman Khrennikov! 🔥\n\nWatch the crew set the scores to beat and battle for a @roguefitness Golden Barbell.\n\nYou do NOT want to miss this incredible battle of fan favorites → https://games.crossfit.com/article/how-watch-2024-crossfit-open\n\nChapters:\n0:00-10:13 - Break\n10:13-12:09 - Introduction to the show\n12:09-21:22 - Open Workout 24.2 recap & unofficial workout winners\n21:22-22:40 - Quarterfinals highlight\n22:40-25:14 - Golden Barbell Award winner for Week 2 Andrew Ciccarelli feature\n25:14-27:35 – Community Throwdown Preview\n27:35-31:38 – Elite Athlete Preview\n36:14-45:56 – Open Workout 24.3 Announcement\n45:56-01:03:25 – Community Throwdown\n01:03:25-01:19:48 – Loewen, Wells, Crouch, and Khrennikov in Open Workout 24.3\n01:19:48-01:23:44 – Presentation of the Golden Barbell & post-WOD interview\n\n—\nThe CrossFit Games are the ultimate proving grounds for the Fittest Man and Fittest Woman on Earth™ and are world-renowned as the definitive test of fitness. Every year since 2007, fans from around the world have attended the multi-day sporting event, streamed the competition online, or watched on ESPN, CBS, or a wide range of international broadcasts. The international field of play has included athletes from more than 120 countries. The CrossFit Games starts in the qualifying round with 300,000+ athletes competing around the world. Throughout the season the field is whittled down to just 560 athletes.\n\nLearn more about the CrossFit Games → https://cf.games/games-learn-more\n\nLearn more about CrossFit → https://www.crossfit.com/what-is-crossfit/?utm_source=social&utm_medium=youtube&utm_campaign=crossfit\n\nFind a CrossFit gym near you → https://www.crossfit.com/map?utm_source=social&utm_medium=youtube&utm_campaign=crossfit\n\nView CrossFit workouts → https://www.crossfit.com/workout?utm_source=social&utm_medium=youtube&utm_campaign=crossfit\n\nSubscribe to CrossFit email newsletters → https://www.crossfit.com/newsletters/?utm_source=social&utm_medium=youtube&utm_campaign=crossfit",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/7Dt3iZluYgA/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/7Dt3iZluYgA/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/7Dt3iZluYgA/hqdefault.jpg",
          width: 480,
          height: 360,
        },
        standard: {
          url: "https://i.ytimg.com/vi/7Dt3iZluYgA/sddefault.jpg",
          width: 640,
          height: 480,
        },
        maxres: {
          url: "https://i.ytimg.com/vi/7Dt3iZluYgA/maxresdefault.jpg",
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "CrossFit Games",
      tags: [
        "Functional Fitness",
        "Fitness",
        "Functional",
        "CrossFit",
        "The CrossFit Games",
        "The Sport of Fitness",
        "Forging Elite Fitness",
        "Sports",
      ],
      categoryId: "17",
      liveBroadcastContent: "none",
      defaultLanguage: "en",
      localized: {
        title: "CrossFit Open Workout 24.3 Live Announcement",
        description:
          "Week 3 of the 2024 CrossFit Open will close out with a bang!\n\nA new matchup will take place for the live announcement of Open Workout #24point3 — get ready to close out the 2024 CrossFit Open with Arielle Loewen, Sydney Wells, Jay Crouch, and Roman Khrennikov! 🔥\n\nWatch the crew set the scores to beat and battle for a @roguefitness Golden Barbell.\n\nYou do NOT want to miss this incredible battle of fan favorites → https://games.crossfit.com/article/how-watch-2024-crossfit-open\n\nChapters:\n0:00-10:13 - Break\n10:13-12:09 - Introduction to the show\n12:09-21:22 - Open Workout 24.2 recap & unofficial workout winners\n21:22-22:40 - Quarterfinals highlight\n22:40-25:14 - Golden Barbell Award winner for Week 2 Andrew Ciccarelli feature\n25:14-27:35 – Community Throwdown Preview\n27:35-31:38 – Elite Athlete Preview\n36:14-45:56 – Open Workout 24.3 Announcement\n45:56-01:03:25 – Community Throwdown\n01:03:25-01:19:48 – Loewen, Wells, Crouch, and Khrennikov in Open Workout 24.3\n01:19:48-01:23:44 – Presentation of the Golden Barbell & post-WOD interview\n\n—\nThe CrossFit Games are the ultimate proving grounds for the Fittest Man and Fittest Woman on Earth™ and are world-renowned as the definitive test of fitness. Every year since 2007, fans from around the world have attended the multi-day sporting event, streamed the competition online, or watched on ESPN, CBS, or a wide range of international broadcasts. The international field of play has included athletes from more than 120 countries. The CrossFit Games starts in the qualifying round with 300,000+ athletes competing around the world. Throughout the season the field is whittled down to just 560 athletes.\n\nLearn more about the CrossFit Games → https://cf.games/games-learn-more\n\nLearn more about CrossFit → https://www.crossfit.com/what-is-crossfit/?utm_source=social&utm_medium=youtube&utm_campaign=crossfit\n\nFind a CrossFit gym near you → https://www.crossfit.com/map?utm_source=social&utm_medium=youtube&utm_campaign=crossfit\n\nView CrossFit workouts → https://www.crossfit.com/workout?utm_source=social&utm_medium=youtube&utm_campaign=crossfit\n\nSubscribe to CrossFit email newsletters → https://www.crossfit.com/newsletters/?utm_source=social&utm_medium=youtube&utm_campaign=crossfit",
      },
      defaultAudioLanguage: "en-US",
    },
    contentDetails: {
      duration: "PT1H24M26S",
      dimension: "2d",
      definition: "hd",
      caption: "false",
      licensedContent: true,
      contentRating: {},
      projection: "rectangular",
    },
    statistics: {
      viewCount: "967960",
      likeCount: "5882",
      favoriteCount: "0",
      commentCount: "125",
    },
  },
  {
    kind: "youtube#video",
    etag: "XZlziqGxOBNc6xvaLVIItZzR2-E",
    id: "XWNAf7yuRDQ",
    snippet: {
      publishedAt: "2024-03-14T16:00:21Z",
      channelId: "UCp68_FLety0O-n9QU6phsgw",
      title: "Digging a Secret Garage Part 3",
      description:
        'Secure your privacy with Surfshark! Enter coupon code COLIN for an extra 3 months free at https://surfshark.deals/colin\n\nGet your furze Merch and MilkinTea Mugs at https://www.colinfurzeshop.com\nExtra Content on the 2nd channel https://www.youtube.com/@2MuchColinFurze\n\nFollow me on Social Media.\nInstagram https://www.instagram.com/realcolinfurze/\nTwitter https://twitter.com/colin_furze\nFacebook https://www.facebook.com/Colin-furze-521680751253584\nTikTok https://vm.tiktok.com/JJ8wSTs/\n\nThanks to Barrett Steel for the supply, if you want steel....buy from them!!\nhttps://www.barrettsteel.com\n\nMusic\n\nTrack 1 is by "Tanners" is called "Remington Steel"\nhttps://open.spotify.com/album/0ea43ctKpgp3XIrYZibtYP?referral=labelaffiliate&utm_source=1101lxWrgxm3&utm_medium=Indie_Distrokid&utm_campaign=labelaffiliate\n\nTrack 2 "Colinfurze"  by a guy named Mat Taylor.......Rock on. \nBut he\'s also in a band lol https://open.spotify.com/album/4nTsP4HsGKTBBk1w2ziWNw?si=wpLV9lBAQoeEI6GeRXwpWw\n\nTrack 3 is called "Mir macht keiner was vor" by "OKA Over"\nhttps://okaover.bandcamp.com/album/over\n\nTrack 4 over surfshark was library music BOOOOO\n\nTrack 5 is called "Where it all Began" by "StereoKeys"\nhttps://www.stereokeys.com\nhttps://www.facebook.com/stereokeys\nhttps://www.instagram.com/stereokeys\n\nTrack 6 "Screw You Mary Lou" by "We Know John"\nhttps://www.instagram.com/weknowjohn/?hl=en\nhttps://www.youtube.com/@weknowjohn257\n\nTrack 7 is called "Ctrl Alt Del" by "Manor Heights"\nhttps://www.manorheights.uk\n\nIn a band, want your music on my videos! Send your tracks to furzemail@yahoo.co.uk as all music on this channel is from viewer\'s.\n\n#colinfurze #secretgarage #secrettunnel',
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/XWNAf7yuRDQ/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/XWNAf7yuRDQ/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/XWNAf7yuRDQ/hqdefault.jpg",
          width: 480,
          height: 360,
        },
        standard: {
          url: "https://i.ytimg.com/vi/XWNAf7yuRDQ/sddefault.jpg",
          width: 640,
          height: 480,
        },
        maxres: {
          url: "https://i.ytimg.com/vi/XWNAf7yuRDQ/maxresdefault.jpg",
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "colinfurze",
      categoryId: "24",
      liveBroadcastContent: "none",
      defaultLanguage: "en-GB",
      localized: {
        title: "Digging a Secret Garage Part 3",
        description:
          'Secure your privacy with Surfshark! Enter coupon code COLIN for an extra 3 months free at https://surfshark.deals/colin\n\nGet your furze Merch and MilkinTea Mugs at https://www.colinfurzeshop.com\nExtra Content on the 2nd channel https://www.youtube.com/@2MuchColinFurze\n\nFollow me on Social Media.\nInstagram https://www.instagram.com/realcolinfurze/\nTwitter https://twitter.com/colin_furze\nFacebook https://www.facebook.com/Colin-furze-521680751253584\nTikTok https://vm.tiktok.com/JJ8wSTs/\n\nThanks to Barrett Steel for the supply, if you want steel....buy from them!!\nhttps://www.barrettsteel.com\n\nMusic\n\nTrack 1 is by "Tanners" is called "Remington Steel"\nhttps://open.spotify.com/album/0ea43ctKpgp3XIrYZibtYP?referral=labelaffiliate&utm_source=1101lxWrgxm3&utm_medium=Indie_Distrokid&utm_campaign=labelaffiliate\n\nTrack 2 "Colinfurze"  by a guy named Mat Taylor.......Rock on. \nBut he\'s also in a band lol https://open.spotify.com/album/4nTsP4HsGKTBBk1w2ziWNw?si=wpLV9lBAQoeEI6GeRXwpWw\n\nTrack 3 is called "Mir macht keiner was vor" by "OKA Over"\nhttps://okaover.bandcamp.com/album/over\n\nTrack 4 over surfshark was library music BOOOOO\n\nTrack 5 is called "Where it all Began" by "StereoKeys"\nhttps://www.stereokeys.com\nhttps://www.facebook.com/stereokeys\nhttps://www.instagram.com/stereokeys\n\nTrack 6 "Screw You Mary Lou" by "We Know John"\nhttps://www.instagram.com/weknowjohn/?hl=en\nhttps://www.youtube.com/@weknowjohn257\n\nTrack 7 is called "Ctrl Alt Del" by "Manor Heights"\nhttps://www.manorheights.uk\n\nIn a band, want your music on my videos! Send your tracks to furzemail@yahoo.co.uk as all music on this channel is from viewer\'s.\n\n#colinfurze #secretgarage #secrettunnel',
      },
      defaultAudioLanguage: "en-GB",
    },
    contentDetails: {
      duration: "PT20M44S",
      dimension: "2d",
      definition: "hd",
      caption: "false",
      licensedContent: true,
      contentRating: {},
      projection: "rectangular",
    },
    statistics: {
      viewCount: "1122831",
      likeCount: "102265",
      favoriteCount: "0",
      commentCount: "6548",
    },
  },
  {
    kind: "youtube#video",
    etag: "_TQ3lGhfMVz6fIAyGVc_r0LbGUY",
    id: "Dr8ZaMAa5jw",
    snippet: {
      publishedAt: "2024-03-14T14:38:14Z",
      channelId: "UCVTomc35agH1SM6kCKzwW_g",
      title: "Replay! SpaceX Starship launches on 3rd integrated test flight",
      description:
        "SpaceX launched Starship atop of its Super Heavy booster from their Starbase facility in South Texas on March 14, 2024. Full Story: https://www.space.com/spacex-starship-third-test-flight-launch\n\nThe gleaming, stainless-steel Starship rocket and its Super Heavy booster, which together stand 400 feet tall (122 meters), were filled with more than 10 million pounds of liquid methane and liquid oxygen propellant during the recent launch dress rehearsal, which was performed at SpaceX's Starbase facility near Boca Chica Beach in southern Texas.\n\nBroadcast courtesy: SpaceX",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/Dr8ZaMAa5jw/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/Dr8ZaMAa5jw/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/Dr8ZaMAa5jw/hqdefault.jpg",
          width: 480,
          height: 360,
        },
        standard: {
          url: "https://i.ytimg.com/vi/Dr8ZaMAa5jw/sddefault.jpg",
          width: 640,
          height: 480,
        },
        maxres: {
          url: "https://i.ytimg.com/vi/Dr8ZaMAa5jw/maxresdefault.jpg",
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "VideoFromSpace",
      tags: [
        "spacex",
        "launch",
        "transporter-10",
        "rideshare",
        "spaceflight",
        "sspaleta",
        "vandenberg",
        "california",
        "landing",
        "space.com",
        "watch live",
      ],
      categoryId: "28",
      liveBroadcastContent: "none",
      localized: {
        title: "Replay! SpaceX Starship launches on 3rd integrated test flight",
        description:
          "SpaceX launched Starship atop of its Super Heavy booster from their Starbase facility in South Texas on March 14, 2024. Full Story: https://www.space.com/spacex-starship-third-test-flight-launch\n\nThe gleaming, stainless-steel Starship rocket and its Super Heavy booster, which together stand 400 feet tall (122 meters), were filled with more than 10 million pounds of liquid methane and liquid oxygen propellant during the recent launch dress rehearsal, which was performed at SpaceX's Starbase facility near Boca Chica Beach in southern Texas.\n\nBroadcast courtesy: SpaceX",
      },
      defaultAudioLanguage: "en-US",
    },
    contentDetails: {
      duration: "PT43M2S",
      dimension: "2d",
      definition: "hd",
      caption: "false",
      licensedContent: true,
      contentRating: {},
      projection: "rectangular",
    },
    statistics: {
      viewCount: "857151",
      likeCount: "11079",
      favoriteCount: "0",
      commentCount: "369",
    },
  },
  {
    kind: "youtube#video",
    etag: "OCAA3YfvgEYvR8thcprCgUaNdJs",
    id: "Evut8BfrZ2U",
    snippet: {
      publishedAt: "2024-03-13T16:00:06Z",
      channelId: "UCtylTUUVIGY_i5afsQYeBZA",
      title: "Eminem - Doomsday 2 (Directed by Cole Bennett)",
      description:
        "Lyrical Lemonade Presents:\n\nEminem - Doomsday Pt. 2 (Official Video)\nDoomsday Pt. 1 (https://www.youtube.com/watch?v=JdXubSf5YUc)\n\n\"All is Yellow\" Out Now: https://lyricallemonade.lnk.to/AllIsYellow\n\nDirected & Edited by Cole Bennett\nSong Produced by Daniyel, John Nocito, Luis Resto, Mel-Man & Dr. Dre\n\nExecutive Producer: Paul Rosenberg, Jake Millan & Cole Bennett\nHead of Production: Krista Worby\nProducers: Krista Worby and Kathy Angstadt \nAssociate Producers: Tracy McNew and John Fisher\nDirector of Photography: Franklin Ricart\nProduction Design: Andre Taylor\nVFX Supervisor: Max Colt\nVFX by Frender\nColor Grade by Josh Bohoskey \n\nProduction Manager: Karl Williams Jr. \nAssistant to Director: Joe Rocha\n1st AC: Mattews di Nelson \n2nd AC: Henry Ture\nSteadicam: Richard Volsky \nGaffer: Jon Gray\nBest Boy Electric: Jake Gottman \nKey Grip: Alan Janush \nBest Boy Grip: Gianluca Petrazzi\nSwing: Mac Rubner\nSet Dressers: Shay Turner, Jonathan Ivory and Cam Harbin\nWardrobe: Jessica Van Assche\nWardrobe Assistant: Laura Finlay\nArtist Stylist: Dawn Boonyachlito\nArtist Grooming: Katrina Lulgjuraj\nVTR: William Costerino \nPlayback: John D'aquino \n2nd AD: Demetrios Anastasiow\nProduction Assistants: Corey Pines, Jarrell Stanton, Brittany Chambers, Jacob Sentowski\nSet Medic: Jim Whittenberg\nLocation Manager: Tom Moisides\nCasting by Ryan Hill Casting \nBackground: \nChad Dorr, Christopher Lewis, Gim Cirpriano, Holly Shwayhat, Justine Miller, Marcus Goddard and Pieter Wingelar\n\nCameos Include: Big Sean, BabyTron, Denzel Curry, Teezo Touchdown, JID, Swae Lee & Cordae\n\n--\n\nOfficial Channel of Lyrical Lemonade \n\nSubscribe for updates on music videos, interviews, performance videos, etc.\n\nLyrical Lemonade's Spotify Playlist:\nhttps://open.spotify.com/user/gh3vdz775oy18ah1wp9ucxsj5/playlist/5UuPeWDR2I8a8pORvW9vmr\n\nLyrical Lemonade Socials:\n\nhttp://www.twitter.com/lyricalemonade\nhttp://www.instagram.com/lyricalemonade\nhttp://www.facebook.com/lyricalemonade\nhttp://www.lyricallemonade.com\n\n\nCole Bennett Socials:\n\nhttp://www.twitter.com/_colebennett_\nhttp://www.instagram.com/colebennett\n\nLENNY ~ a hidden character representing happiness & good energy\nhttp://instagram.com/lenny",
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/Evut8BfrZ2U/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/Evut8BfrZ2U/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/Evut8BfrZ2U/hqdefault.jpg",
          width: 480,
          height: 360,
        },
        standard: {
          url: "https://i.ytimg.com/vi/Evut8BfrZ2U/sddefault.jpg",
          width: 640,
          height: 480,
        },
        maxres: {
          url: "https://i.ytimg.com/vi/Evut8BfrZ2U/maxresdefault.jpg",
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "Lyrical Lemonade",
      tags: [
        "yellow curtain",
        "eminem",
        "new music",
        "lyrical lemonade",
        "cole bennett",
        "doomsday 2",
        "hip hop",
        "rap",
        "music video",
        "j cole",
        "forever",
      ],
      categoryId: "24",
      liveBroadcastContent: "none",
      localized: {
        title: "Eminem - Doomsday 2 (Directed by Cole Bennett)",
        description:
          "Lyrical Lemonade Presents:\n\nEminem - Doomsday Pt. 2 (Official Video)\nDoomsday Pt. 1 (https://www.youtube.com/watch?v=JdXubSf5YUc)\n\n\"All is Yellow\" Out Now: https://lyricallemonade.lnk.to/AllIsYellow\n\nDirected & Edited by Cole Bennett\nSong Produced by Daniyel, John Nocito, Luis Resto, Mel-Man & Dr. Dre\n\nExecutive Producer: Paul Rosenberg, Jake Millan & Cole Bennett\nHead of Production: Krista Worby\nProducers: Krista Worby and Kathy Angstadt \nAssociate Producers: Tracy McNew and John Fisher\nDirector of Photography: Franklin Ricart\nProduction Design: Andre Taylor\nVFX Supervisor: Max Colt\nVFX by Frender\nColor Grade by Josh Bohoskey \n\nProduction Manager: Karl Williams Jr. \nAssistant to Director: Joe Rocha\n1st AC: Mattews di Nelson \n2nd AC: Henry Ture\nSteadicam: Richard Volsky \nGaffer: Jon Gray\nBest Boy Electric: Jake Gottman \nKey Grip: Alan Janush \nBest Boy Grip: Gianluca Petrazzi\nSwing: Mac Rubner\nSet Dressers: Shay Turner, Jonathan Ivory and Cam Harbin\nWardrobe: Jessica Van Assche\nWardrobe Assistant: Laura Finlay\nArtist Stylist: Dawn Boonyachlito\nArtist Grooming: Katrina Lulgjuraj\nVTR: William Costerino \nPlayback: John D'aquino \n2nd AD: Demetrios Anastasiow\nProduction Assistants: Corey Pines, Jarrell Stanton, Brittany Chambers, Jacob Sentowski\nSet Medic: Jim Whittenberg\nLocation Manager: Tom Moisides\nCasting by Ryan Hill Casting \nBackground: \nChad Dorr, Christopher Lewis, Gim Cirpriano, Holly Shwayhat, Justine Miller, Marcus Goddard and Pieter Wingelar\n\nCameos Include: Big Sean, BabyTron, Denzel Curry, Teezo Touchdown, JID, Swae Lee & Cordae\n\n--\n\nOfficial Channel of Lyrical Lemonade \n\nSubscribe for updates on music videos, interviews, performance videos, etc.\n\nLyrical Lemonade's Spotify Playlist:\nhttps://open.spotify.com/user/gh3vdz775oy18ah1wp9ucxsj5/playlist/5UuPeWDR2I8a8pORvW9vmr\n\nLyrical Lemonade Socials:\n\nhttp://www.twitter.com/lyricalemonade\nhttp://www.instagram.com/lyricalemonade\nhttp://www.facebook.com/lyricalemonade\nhttp://www.lyricallemonade.com\n\n\nCole Bennett Socials:\n\nhttp://www.twitter.com/_colebennett_\nhttp://www.instagram.com/colebennett\n\nLENNY ~ a hidden character representing happiness & good energy\nhttp://instagram.com/lenny",
      },
    },
    contentDetails: {
      duration: "PT2M34S",
      dimension: "2d",
      definition: "hd",
      caption: "false",
      licensedContent: true,
      regionRestriction: {
        blocked: ["BY", "RU"],
      },
      contentRating: {},
      projection: "rectangular",
    },
    statistics: {
      viewCount: "2036324",
      likeCount: "162923",
      favoriteCount: "0",
      commentCount: "12767",
    },
  },
  {
    kind: "youtube#video",
    etag: "hIO_rc66mRtAoztfEUmcAMk8FGM",
    id: "e9nFYCO7tBU",
    snippet: {
      publishedAt: "2024-03-14T15:31:39Z",
      channelId: "UCH1oRy1dINbMVp3UFWrKP0w",
      title: "Regina King talks about her grief after son’s death",
      description:
        'The actress opens up about heartbreak she experienced after losing her son to suicide and her role in her new movie, "Shirley."\nREAD MORE: https://tinyurl.com/2sudczx3\n\n\nSUBSCRIBE: https://bit.ly/2Zq0dU5 \n\nSIGN UP to get the daily GMA Wake-Up Newsletter: \nhttps://gma.abc/2Vzcd5j\n\nVISIT GMA: https://www.goodmorningamerica.com\n\nFOLLOW:\nTikTok: https://tiktok.com/@gma\nInstagram: https://instagram.com/GoodMorningAmerica\nFacebook: https://facebook.com/GoodMorningAmerica\nThreads: https://www.threads.net/@goodmorningamerica\nX: https://twitter.com/gma',
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/e9nFYCO7tBU/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/e9nFYCO7tBU/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/e9nFYCO7tBU/hqdefault.jpg",
          width: 480,
          height: 360,
        },
        standard: {
          url: "https://i.ytimg.com/vi/e9nFYCO7tBU/sddefault.jpg",
          width: 640,
          height: 480,
        },
        maxres: {
          url: "https://i.ytimg.com/vi/e9nFYCO7tBU/maxresdefault.jpg",
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "Good Morning America",
      tags: [
        "ABC",
        "GMA",
        "King",
        "News",
        "Regina",
        "Shirley",
        "actress",
        "grief",
        "health",
        "heartbreak",
        "mental",
        "movie",
        "p_cmsid=2494279",
        "p_vid=news-108106689",
        "son",
        "suicide",
        "regina king",
        "regina king son",
        "regina king son ian",
        "regina king oscar",
        "regina king shirley",
        "How did Regina King lose her son?",
        "regina king son age",
        "shirley chilsom",
        "new regina king movie",
        "good morning america",
        "abc news",
      ],
      categoryId: "24",
      liveBroadcastContent: "none",
      localized: {
        title: "Regina King talks about her grief after son’s death",
        description:
          'The actress opens up about heartbreak she experienced after losing her son to suicide and her role in her new movie, "Shirley."\nREAD MORE: https://tinyurl.com/2sudczx3\n\n\nSUBSCRIBE: https://bit.ly/2Zq0dU5 \n\nSIGN UP to get the daily GMA Wake-Up Newsletter: \nhttps://gma.abc/2Vzcd5j\n\nVISIT GMA: https://www.goodmorningamerica.com\n\nFOLLOW:\nTikTok: https://tiktok.com/@gma\nInstagram: https://instagram.com/GoodMorningAmerica\nFacebook: https://facebook.com/GoodMorningAmerica\nThreads: https://www.threads.net/@goodmorningamerica\nX: https://twitter.com/gma',
      },
    },
    contentDetails: {
      duration: "PT10M11S",
      dimension: "2d",
      definition: "hd",
      caption: "false",
      licensedContent: true,
      contentRating: {},
      projection: "rectangular",
    },
    statistics: {
      viewCount: "523025",
      likeCount: "19629",
      favoriteCount: "0",
      commentCount: "2230",
    },
  },
];
